function(includeSouffle)
  set(CMAKE_SYSTEM_PROCESSOR ${SWIFT_HOST_VARIANT_ARCH})
  set(CMAKE_OSX_ARCHITECTURES ${SWIFT_HOST_VARIANT_ARCH})
  set(CMAKE_C_COMPILER_TARGET ${SWIFT_HOST_TRIPLE})
  set(CMAKE_CXX_COMPILER_TARGET ${SWIFT_HOST_TRIPLE})
  set(CMAKE_Swift_COMPILER_TARGET ${SWIFT_HOST_TRIPLE})
  set(CMAKE_LIBRARY_OUTPUT_DIRECTORY "${SWIFT_HOST_LIBRARIES_DEST_DIR}/compiler")
  set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY "${SWIFT_HOST_LIBRARIES_DEST_DIR}/compiler")

  file(TO_CMAKE_PATH "/Users/gaborhorvath/dev/swift-project/souffle" souffle_path)
  FetchContent_Declare(CompilerSouffle SOURCE_DIR "${souffle_path}")
  FetchContent_MakeAvailable(CompilerSouffle)
endfunction()
includeSouffle()
