.type loan <: unsigned
.type origin <: unsigned
.type location <: unsigned
.type function <: symbol

.type programPoint <: unsigned
.type context <: symbol

// IR

// Lifetime facts
.decl Issue(l: loan, o: origin, loc: location, point: programPoint, c: context)
.input Issue
.decl Expire(l: loan, loc: location, point: programPoint, c: context)
.input Expire
.decl Assign(src: origin, dest: origin, c: context)
.input Assign
.decl Return(callerLoan: loan, callerOrigin: origin, callerPoint: programPoint, callerContext: context, calleeOrigin: origin, calleeContext: context)
.input Return
.decl Use(o: origin, loc: location, point: programPoint, c: context)
.input Use
.decl Deallocate(o: origin, loc: location, p: programPoint, c: context)
.input Deallocate
.decl Pass(callerOrigin: origin, callerPoint: programPoint, callerContext: context, calleeLoan: loan, calleeOrigin: origin, calleeContext: context)
.input Pass

// Control flow structure
.decl Edge(from: programPoint, to: programPoint, c: context)
.input Edge

// Computed relations

.decl LoansAtOrigin(l: loan, o: origin, c: context)
.output LoansAtOrigin
LoansAtOrigin(l, o, c) :- Issue(l, o, _, _, c).
LoansAtOrigin(l, o, c) :- Return(l, o, _, c, _, _).
LoansAtOrigin(l, o, c) :- Pass(_, _, _, l, o, c).
LoansAtOrigin(l, o2, c) :- LoansAtOrigin(l, o1, c), Assign(o1, o2, c).

.decl LoansPassed(fromLoan: loan, fromContext: context, toLoan: loan, toContext: context)
.output LoansPassed
// Base
LoansPassed(callerLoan, callerContext, callerLoan, callerContext) :- 
  Issue(callerLoan, _, _, _, callerContext).
LoansPassed(callerLoan, callerContext, callerLoan, callerContext) :- 
  Return(callerLoan, _, _, callerContext, _, _).
LoansPassed(calleeLoan, calleeContext, calleeLoan, calleeContext) :- 
  Pass(_, _, _, calleeLoan, _, calleeContext).
// Pass directly
LoansPassed(callerLoan, callerContext, calleeLoan, calleeContext) :-
  LoansAtOrigin(callerLoan, callerOrigin, callerContext),
  Pass(callerOrigin, _, callerContext, calleeLoan, _, calleeContext).
LoansPassed(calleeLoan, calleeContext, callerLoan, callerContext) :-
  LoansAtOrigin(calleeLoan, calleeReturnOrigin, calleeContext),
  Return(callerLoan, _, _, callerContext, calleeReturnOrigin, calleeContext).
// Transitive closure
LoansPassed(callerLoan, callerContext, indirectCalleeLoan, indirectCalleeContext) :-
  LoansPassed(callerLoan, callerContext, directCalleeLoan, directCalleeContext),
  LoansPassed(directCalleeLoan, directCalleeContext, indirectCalleeLoan, indirectCalleeContext).

.decl Alias(l1: loan, l2: loan, p: programPoint, c: context)
.output Alias
Alias(l1, l2, p, c) :- Pass(o, p, c, calleeLoan, _, calleeContext), LoansAtOrigin(l1, o, c),
  Return(l2, _, p, c, returnOrigin, calleeContext), LoansAtOrigin(calleeLoan, returnOrigin, calleeContext).
Alias(l1, l3, p, c) :- Alias(l1, l2, p, c), Alias(l2, l3, p, c).
Alias(l1, l2, p, c) :- Alias(l2, l1, p, c).

.decl ExpiredLoanAt(l: loan, p: programPoint, c: context)
.output ExpiredLoanAt
ExpiredLoanAt(l, p, c) :- Expire(l, _, p, c).
ExpiredLoanAt(l, p2, c) :- ExpiredLoanAt(l, p1, c), Edge(p1, p2, c), !Issue(l, _, _, p2, c).
// Manual memory management
ExpiredLoanAt(l, p, c) :- Deallocate(o, _, p, c), LoansAtOrigin(l, o, c).
// Expired in a function call
ExpiredLoanAt(l, p, callerContext) :-  Pass(o, p, callerContext, calleeLoan, _, calleeContext), LoansAtOrigin(l, o, callerContext),
  ExpiredLoanAt(calleeLoan, _, calleeContext).
ExpiredLoanAt(l, p, c) :- ExpiredLoanAt(alias, p, c), Alias(alias, l, p, c).

// Output
.decl UseDefaulted(useLoc: location, usePoint: programPoint,
                   expireLoc: location, expirePoint: programPoint,
                   issueLoc: location, issuePoint: programPoint)
.output UseDefaulted
UseDefaulted(useLoc, usePoint, expireLoc, expirePoint, issueLoc, issuePoint) :- 
  ExpiredLoanAt(l, usePoint, c), Use(o, useLoc, usePoint, c), LoansAtOrigin(l, o, c),
  Issue(l, _, issueLoc, issuePoint, c), Expire(l, expireLoc, expirePoint, c).

// Manual memory management
UseDefaulted(useLoc, usePoint, expireLoc, expirePoint, issueLoc, issuePoint) :- 
  Issue(issueLoan, _, issueLoc, issuePoint, issueContext), LoansPassed(issueLoan, issueContext, deallocLoan, deallocContext),
  Deallocate(o2, expireLoc, expirePoint, deallocContext), LoansAtOrigin(deallocLoan, o2, deallocContext),
  LoansPassed(issueLoan, issueContext, usedLoan, usedContext),
  Use(o, useLoc, usePoint, usedContext), LoansAtOrigin(usedLoan, o, usedContext), ExpiredLoanAt(usedLoan, usePoint, usedContext).
