.type Loan <: unsigned
.type Origin <: unsigned
.type Location <: unsigned
.type ProgramPoint <: unsigned
.type Context <: symbol

// IR

// Lifetime facts
.decl Issue(l: Loan, o: Origin, loc: Location, point: ProgramPoint, c: Context)
.input Issue
.decl Expire(l: Loan, loc: Location, point: ProgramPoint, c: Context)
.input Expire
.decl Assign(src: Origin, dest: Origin, c: Context)
.input Assign
.decl Return(callerLoan: Loan, callerOrigin: Origin, callerPoint: ProgramPoint, callerContext: Context, calleeOrigin: Origin, calleeContext: Context)
.input Return
.decl Use(o: Origin, loc: Location, point: ProgramPoint, c: Context)
.input Use
.decl Deallocate(o: Origin, loc: Location, p: ProgramPoint, c: Context)
.input Deallocate
.decl Pass(callerOrigin: Origin, callerPoint: ProgramPoint, callerContext: Context, calleeLoan: Loan, calleeOrigin: Origin, calleeContext: Context)
.input Pass

// Control flow structure
.decl Edge(from: ProgramPoint, to: ProgramPoint, c: Context)
.input Edge

// Computed relations

.decl LoansAtOrigin(l: Loan, o: Origin, c: Context)
LoansAtOrigin(l, o, c) :- Issue(l, o, _, _, c).
LoansAtOrigin(l, o, c) :- Return(l, o, _, c, _, _).
LoansAtOrigin(l, o, c) :- Pass(_, _, _, l, o, c).
LoansAtOrigin(l, o2, c) :- LoansAtOrigin(l, o1, c), Assign(o1, o2, c).

.decl LoansPassed(fromLoan: Loan, fromContext: Context, toLoan: Loan, toContext: Context)
// Base
LoansPassed(callerLoan, callerContext, callerLoan, callerContext) :- 
  Issue(callerLoan, _, _, _, callerContext).
LoansPassed(callerLoan, callerContext, callerLoan, callerContext) :- 
  Return(callerLoan, _, _, callerContext, _, _).
LoansPassed(calleeLoan, calleeContext, calleeLoan, calleeContext) :- 
  Pass(_, _, _, calleeLoan, _, calleeContext).
// Pass directly
LoansPassed(callerLoan, callerContext, calleeLoan, calleeContext) :-
  LoansAtOrigin(callerLoan, callerOrigin, callerContext),
  Pass(callerOrigin, _, callerContext, calleeLoan, _, calleeContext).
LoansPassed(calleeLoan, calleeContext, callerLoan, callerContext) :-
  LoansAtOrigin(calleeLoan, calleeReturnOrigin, calleeContext),
  Return(callerLoan, _, _, callerContext, calleeReturnOrigin, calleeContext).
// Transitive closure
LoansPassed(callerLoan, callerContext, indirectCalleeLoan, indirectCalleeContext) :-
  LoansPassed(callerLoan, callerContext, directCalleeLoan, directCalleeContext),
  LoansPassed(directCalleeLoan, directCalleeContext, indirectCalleeLoan, indirectCalleeContext).

.decl Alias(l1: Loan, l2: Loan, p: ProgramPoint, c: Context)
Alias(l1, l2, p, c) :- Pass(o, p, c, calleeLoan, _, calleeContext), LoansAtOrigin(l1, o, c),
  Return(l2, _, p, c, returnOrigin, calleeContext), LoansAtOrigin(calleeLoan, returnOrigin, calleeContext).
Alias(l1, l3, p, c) :- Alias(l1, l2, p, c), Alias(l2, l3, p, c).
Alias(l1, l2, p, c) :- Alias(l2, l1, p, c).
Alias(l1, l2, p2, c) :- Alias(l1, l2, p1, c), Edge(p1, p2, c).

.decl ExpiredLoanAt(l: Loan, p: ProgramPoint, c: Context)
ExpiredLoanAt(l, p, c) :- Expire(l, _, p, c).
ExpiredLoanAt(l, p2, c) :- ExpiredLoanAt(l, p1, c), Edge(p1, p2, c), !Issue(l, _, _, p2, c).
// Manual memory management
ExpiredLoanAt(l, p, c) :- Deallocate(o, _, p, c), LoansAtOrigin(l, o, c).
// Expired in a function call
ExpiredLoanAt(l, p, callerContext) :-  Pass(o, p, callerContext, calleeLoan, _, calleeContext), LoansAtOrigin(l, o, callerContext),
  ExpiredLoanAt(calleeLoan, _, calleeContext).
ExpiredLoanAt(l, p, c) :- ExpiredLoanAt(alias, p, c), Alias(alias, l, p, c).

// Output
.decl UseDefaulted(useLoc: Location, usePoint: ProgramPoint,
                   expireLoc: Location, expirePoint: ProgramPoint,
                   issueLoc: Location, issuePoint: ProgramPoint)
.output UseDefaulted
UseDefaulted(useLoc, usePoint, expireLoc, expirePoint, issueLoc, issuePoint) :- 
  ExpiredLoanAt(l, usePoint, c), Use(o, useLoc, usePoint, c), LoansAtOrigin(l, o, c),
  Issue(l, _, issueLoc, issuePoint, c), Expire(l, expireLoc, expirePoint, c).

// Manual memory management
UseDefaulted(useLoc, usePoint, expireLoc, expirePoint, issueLoc, issuePoint) :- 
  Issue(issueLoan, _, issueLoc, issuePoint, issueContext), LoansPassed(issueLoan, issueContext, deallocLoan, deallocContext),
  Deallocate(o2, expireLoc, expirePoint, deallocContext), LoansAtOrigin(deallocLoan, o2, deallocContext),
  LoansPassed(issueLoan, issueContext, usedLoan, usedContext),
  Use(o, useLoc, usePoint, usedContext), LoansAtOrigin(usedLoan, o, usedContext), ExpiredLoanAt(usedLoan, usePoint, usedContext).
